# ruff: noqa: D100
from typing import TYPE_CHECKING

from good_ass_pydantic_integrator import load

from .optional_models import LodpTitleAndPlansPageModel as OptionalModel
from .strict_models import LodpTitleAndPlansPageModel as StrictModel

if TYPE_CHECKING:
    from .strict_models import (
        Actors,
        Artwork,
        AudioTrack,
        BillboardOrStoryArt1280,
        BillboardOrStoryArt12801,
        BillboardOrStoryArt960,
        Boxshot300,
        BrandLogoCropped48h,
        ContentAdvisory,
        CoreGenres,
        Creators,
        Directors,
        EclipseBillboardRedux1280,
        EclipseBillboardRedux1920,
        Edge,
        Edge1,
        Edge2,
        Edge3,
        Edge4,
        Edge5,
        Edge6,
        Edge7,
        Episodes,
        FocalPoint,
        Genres,
        LodpTitleAndPlansPageModel,
        LogoStackCropped350,
        MediaTracks,
        MerchStill300,
        Node,
        Node1,
        Node2,
        Node3,
        Node4,
        Node6,
        Node7,
        PageInfo,
        PlayableVideo,
        PrimaryGenres,
        PromoVideo,
        Seasons,
        ShareTaglineMessage,
        SimilarVideo,
        Subtitle,
        Tag,
        TaglineMessage,
        ThumbnailClips,
        Trailers,
        TudumTitle,
        Video,
    )
else:
    from .optional_models import (
        Actors,
        Artwork,
        AudioTrack,
        BillboardOrStoryArt1280,
        BillboardOrStoryArt12801,
        BillboardOrStoryArt960,
        Boxshot300,
        BrandLogoCropped48h,
        ContentAdvisory,
        CoreGenres,
        Creators,
        Directors,
        EclipseBillboardRedux1280,
        EclipseBillboardRedux1920,
        Edge,
        Edge1,
        Edge2,
        Edge3,
        Edge4,
        Edge5,
        Edge6,
        Edge7,
        Episodes,
        FocalPoint,
        Genres,
        LodpTitleAndPlansPageModel,
        LogoStackCropped350,
        MediaTracks,
        MerchStill300,
        Node,
        Node1,
        Node2,
        Node3,
        Node4,
        Node6,
        Node7,
        PageInfo,
        PlayableVideo,
        PrimaryGenres,
        PromoVideo,
        Seasons,
        ShareTaglineMessage,
        SimilarVideo,
        Subtitle,
        Tag,
        TaglineMessage,
        ThumbnailClips,
        Trailers,
        TudumTitle,
        Video,
    )

__all__ = [
    "Actors",
    "Artwork",
    "AudioTrack",
    "BillboardOrStoryArt1280",
    "BillboardOrStoryArt12801",
    "BillboardOrStoryArt960",
    "Boxshot300",
    "BrandLogoCropped48h",
    "ContentAdvisory",
    "CoreGenres",
    "Creators",
    "Directors",
    "EclipseBillboardRedux1280",
    "EclipseBillboardRedux1920",
    "Edge",
    "Edge1",
    "Edge2",
    "Edge3",
    "Edge4",
    "Edge5",
    "Edge6",
    "Edge7",
    "Episodes",
    "FocalPoint",
    "Genres",
    "LodpTitleAndPlansPageModel",
    "LogoStackCropped350",
    "MediaTracks",
    "MerchStill300",
    "Node",
    "Node1",
    "Node2",
    "Node3",
    "Node4",
    "Node6",
    "Node7",
    "PageInfo",
    "PlayableVideo",
    "PrimaryGenres",
    "PromoVideo",
    "Seasons",
    "ShareTaglineMessage",
    "SimilarVideo",
    "Subtitle",
    "Tag",
    "TaglineMessage",
    "ThumbnailClips",
    "Trailers",
    "TudumTitle",
    "Video",
    "model_validate_json",
]


def model_validate_json(data: str | bytes | object, log_id: str) -> LodpTitleAndPlansPageModel:
    """Read a downloaded file into LodpTitleAndPlansPageModel."""
    return load.model_validate_json(StrictModel, OptionalModel, data, log_id)
