"""LodpTitleAndPlansPageModel, strict to a type checker, all-optional at runtime.

A type checker reads the strict model, so every field carries the type and
the requiredness the schema recorded. At runtime the all-optional copy is imported
instead, so a response that has drifted still parses and a field the data is
missing is None despite what its type hint says.
"""

from typing import TYPE_CHECKING

from good_ass_pydantic_integrator import load

from .optional_models import LodpTitleAndPlansPageModel as OptionalModel
from .strict_models import LodpTitleAndPlansPageModel as StrictModel

if TYPE_CHECKING:
    from .strict_models import (
        Actors,
        Artwork,
        Attributes,
        AudioTrack,
        BillboardOrStoryArt1280,
        BillboardOrStoryArt12801,
        BillboardOrStoryArt960,
        Boxshot300,
        BrandLogoCropped48h,
        Collection,
        ContentAdvisory,
        CoreGenres,
        Creators,
        Data,
        Directors,
        EclipseBillboardRedux1280,
        EclipseBillboardRedux1920,
        Edge,
        Edge1,
        Edge2,
        Edge3,
        Edge4,
        Edge5,
        Edge6,
        Edge7,
        Edge8,
        Episodes,
        FocalPoint,
        Genres,
        LodpTitleAndPlansPageModel,
        LogoStackCropped350,
        MediaTracks,
        MerchStill300,
        Node,
        Node1,
        Node2,
        Node3,
        Node4,
        Node6,
        Node7,
        Node8,
        PageInfo,
        Plan,
        Plans,
        PlayableVideo,
        Price,
        PrimaryGenres,
        PromoVideo,
        Seasons,
        ShareTaglineMessage,
        SimilarVideo,
        Subtitle,
        Tag,
        TaglineMessage,
        ThumbnailClips,
        Trailers,
        TrifectaRows,
        TudumTitle,
        Video,
        Video1,
        Video2,
    )
else:
    from .optional_models import (
        Actors,
        Artwork,
        Attributes,
        AudioTrack,
        BillboardOrStoryArt1280,
        BillboardOrStoryArt12801,
        BillboardOrStoryArt960,
        Boxshot300,
        BrandLogoCropped48h,
        Collection,
        ContentAdvisory,
        CoreGenres,
        Creators,
        Data,
        Directors,
        EclipseBillboardRedux1280,
        EclipseBillboardRedux1920,
        Edge,
        Edge1,
        Edge2,
        Edge3,
        Edge4,
        Edge5,
        Edge6,
        Edge7,
        Edge8,
        Episodes,
        FocalPoint,
        Genres,
        LodpTitleAndPlansPageModel,
        LogoStackCropped350,
        MediaTracks,
        MerchStill300,
        Node,
        Node1,
        Node2,
        Node3,
        Node4,
        Node6,
        Node7,
        Node8,
        PageInfo,
        Plan,
        Plans,
        PlayableVideo,
        Price,
        PrimaryGenres,
        PromoVideo,
        Seasons,
        ShareTaglineMessage,
        SimilarVideo,
        Subtitle,
        Tag,
        TaglineMessage,
        ThumbnailClips,
        Trailers,
        TrifectaRows,
        TudumTitle,
        Video,
        Video1,
        Video2,
    )

__all__ = [
    "Actors",
    "Artwork",
    "Attributes",
    "AudioTrack",
    "BillboardOrStoryArt1280",
    "BillboardOrStoryArt12801",
    "BillboardOrStoryArt960",
    "Boxshot300",
    "BrandLogoCropped48h",
    "Collection",
    "ContentAdvisory",
    "CoreGenres",
    "Creators",
    "Data",
    "Directors",
    "EclipseBillboardRedux1280",
    "EclipseBillboardRedux1920",
    "Edge",
    "Edge1",
    "Edge2",
    "Edge3",
    "Edge4",
    "Edge5",
    "Edge6",
    "Edge7",
    "Edge8",
    "Episodes",
    "FocalPoint",
    "Genres",
    "LodpTitleAndPlansPageModel",
    "LogoStackCropped350",
    "MediaTracks",
    "MerchStill300",
    "Node",
    "Node1",
    "Node2",
    "Node3",
    "Node4",
    "Node6",
    "Node7",
    "Node8",
    "PageInfo",
    "Plan",
    "Plans",
    "PlayableVideo",
    "Price",
    "PrimaryGenres",
    "PromoVideo",
    "Seasons",
    "ShareTaglineMessage",
    "SimilarVideo",
    "Subtitle",
    "Tag",
    "TaglineMessage",
    "ThumbnailClips",
    "Trailers",
    "TrifectaRows",
    "TudumTitle",
    "Video",
    "Video1",
    "Video2",
    "model_validate_json",
]


def model_validate_json(data: str | bytes | object, log_id: str) -> LodpTitleAndPlansPageModel:
    """Read a downloaded file into LodpTitleAndPlansPageModel."""
    return load.model_validate_json(StrictModel, OptionalModel, data, log_id)
