# ruff: noqa: D100
from typing import TYPE_CHECKING

from good_ass_pydantic_integrator import load

from .optional_models import DetailModalModel as OptionalModel
from .strict_models import DetailModalModel as StrictModel

if TYPE_CHECKING:
    from .strict_models import (
        Boxart,
        BoxartHighRes,
        BrandLogoSmall,
        BroadcastInfo,
        Cast,
        ContentAdvisory,
        ContentWarning,
        ContextualSynopsis,
        Creators,
        CurrentEpisode,
        DetailModalModel,
        Directors,
        Edge,
        Edge1,
        Edge2,
        Edge3,
        Edge4,
        Edge5,
        Episodes,
        FocalPoint,
        GenreTags,
        MoodTag,
        MostLikedMessage,
        Node,
        Node4,
        Node5,
        PageInfo,
        ParentSeason,
        Reason,
        Seasons,
        Sibling,
        Similar,
        StoryArt,
        SupplementalVideosList,
        TaglineMessage,
        TitleGroupMembership,
        TitleLogoBranded,
        TitleLogoUnbranded,
        Writers,
    )
else:
    from .optional_models import (
        Boxart,
        BoxartHighRes,
        BrandLogoSmall,
        BroadcastInfo,
        Cast,
        ContentAdvisory,
        ContentWarning,
        ContextualSynopsis,
        Creators,
        CurrentEpisode,
        DetailModalModel,
        Directors,
        Edge,
        Edge1,
        Edge2,
        Edge3,
        Edge4,
        Edge5,
        Episodes,
        FocalPoint,
        GenreTags,
        MoodTag,
        MostLikedMessage,
        Node,
        Node4,
        Node5,
        PageInfo,
        ParentSeason,
        Reason,
        Seasons,
        Sibling,
        Similar,
        StoryArt,
        SupplementalVideosList,
        TaglineMessage,
        TitleGroupMembership,
        TitleLogoBranded,
        TitleLogoUnbranded,
        Writers,
    )

__all__ = [
    "Boxart",
    "BoxartHighRes",
    "BrandLogoSmall",
    "BroadcastInfo",
    "Cast",
    "ContentAdvisory",
    "ContentWarning",
    "ContextualSynopsis",
    "Creators",
    "CurrentEpisode",
    "DetailModalModel",
    "Directors",
    "Edge",
    "Edge1",
    "Edge2",
    "Edge3",
    "Edge4",
    "Edge5",
    "Episodes",
    "FocalPoint",
    "GenreTags",
    "MoodTag",
    "MostLikedMessage",
    "Node",
    "Node4",
    "Node5",
    "PageInfo",
    "ParentSeason",
    "Reason",
    "Seasons",
    "Sibling",
    "Similar",
    "StoryArt",
    "SupplementalVideosList",
    "TaglineMessage",
    "TitleGroupMembership",
    "TitleLogoBranded",
    "TitleLogoUnbranded",
    "Writers",
    "model_validate_json",
]


def model_validate_json(data: str | bytes | object, log_id: str) -> DetailModalModel:
    """Read a downloaded file into DetailModalModel."""
    return load.model_validate_json(StrictModel, OptionalModel, data, log_id)
